export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const FETCH_CHANNELS_DATA = 'FETCH_CHANNELS_DATA';
export const FETCH_TESTS_DATA = 'FETCH_TESTS_DATA';
export const CALC_UTILIZATION = 'CALC_UTILIZATION';
