export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const FETCH_CHANNELS_DATA = 'FETCH_CHANNELS_DATA';
export const FETCH_TESTS_DATA = 'FETCH_TESTS_DATA';
export const SET_TOTAL_CHANNELS = 'SET_TOTAL_CHANNELS';
export const CALC_UTILIZATION = 'CALC_UTILIZATION';
export const TOGGLE_WEEKENDS = 'TOGGLE_WEEKENDS';
